version: '3'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./home:/home
    ports:
      - 3306:3306
